# Generated by Django 5.2.1 on 2025-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education')], default='work', max_length=10)),
                ('title', models.CharField(help_text='e.g., Software Engineer or B.S. in Computer Science', max_length=200)),
                ('company', models.CharField(help_text='e.g., Google or University of California', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current.', null=True)),
                ('description', models.TextField(help_text='Use bullet points or a short paragraph.')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('title', models.CharField(help_text='e.g., Full-Stack Developer', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short biography about yourself.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('cv', models.FileField(blank=True, help_text='Upload your CV/Resume.', null=True, upload_to='cv/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Info',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Projects with lower numbers appear first.')),
                ('technologies', models.ManyToManyField(related_name='projects', to='core.skill')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
